name: Build and Push to Docker Hub

on:
  # 1. Cho phép bấm nút chạy bằng tay trên web GitHub
  workflow_dispatch:

  # 2. Lắng nghe sự kiện push
  push:
    branches:
      - "main"    # Nhánh chính
    tags:
      - "v*"      # Chấp nhận mọi tag bắt đầu bằng v (vd: v1, v1.0, v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    
    # --- ĐIỀU KIỆN CHẠY (QUAN TRỌNG) ---
    # Chỉ chạy khi: (Là Tag) HOẶC (Có từ khóa [build]) HOẶC (Bấm nút bằng tay)
    if: >
      startsWith(github.ref, 'refs/tags/') ||
      contains(github.event.head_commit.message, '[build]') ||
      github.event_name == 'workflow_dispatch'
    # -----------------------------------

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- XỬ LÝ TÊN IMAGE TỰ ĐỘNG ---
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: patcoder97/fhs-backend
          tags: |
            # 1. Nếu là Tag (v1.0) -> Lấy đúng tên v1.0
            type=ref,event=tag
            
            # 2. Nếu là Tag -> Tự động thêm tag 'latest'
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

            # 3. Nếu là nhánh Main (có [build]) -> Đặt là 'dev'
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
